---
- name: Template Netplan config
  loop: "{{ system.netplan | dict2items }}"
  loop_control:
    label: "{{ dest }}"
  vars:
    dest: "/etc/netplan/{{ item.key }}"
  ansible.builtin.copy:
    mode: "0644"
    owner: root
    content: |
      {{ item.value | to_nice_yaml(indent=2) }}
    dest: "{{ dest }}"
  register: system_template_netplan_config_result

- name: Apply Netplan config
  when: system_template_netplan_config_result.changed
  changed_when: yes
  ansible.builtin.command:
    cmd: netplan apply
