---
- name: Create directory for Ansible facts
  ansible.builtin.file:
    mode: "0755"
    owner: root
    path: "/etc/ansible/facts.d"
    state: directory

- name: Template proServer fact
  ansible.builtin.template:
    owner: root
    src: proserver.fact.py
    dest: "/usr/local/bin/proserver-facts"
    mode: a+x
  register: system_template_proserver_fact_result

- name: Link proServer fact
  ansible.builtin.file:
    src: /usr/local/bin/proserver-facts
    dest: "/etc/ansible/facts.d/proserver.fact"
    state: link
  register: system_link_proserver_fact_result

- name: Reload facts
  when: system_template_proserver_fact_result.changed or system_link_proserver_fact_result.changed
  changed_when: system_template_proserver_fact_result.changed or system_link_proserver_fact_result.changed
  ansible.builtin.setup: {}
