---
- name: Make sure that sshd is installed (Debian-based)
  when: ansible_os_family == "Debian"
  ansible.builtin.package:
    name: openssh-server

- name: Make sure that the custom sshd configuration is included
  notify:
    - Restart sshd
  ansible.builtin.lineinfile:
    validate: "sshd -T -f %s"
    path: /etc/ssh/sshd_config
    line: "Include /etc/ssh/sshd_config.d/*"
    insertbefore: "BOF"

- name: Create the config folder
  ansible.builtin.file:
    path: /etc/ssh/sshd_config.d
    state: directory
    owner: root
    mode: "0755"

- name: Template the sshd configuration
  notify:
    - Restart sshd
  ansible.builtin.copy:
    validate: "{{ 'sshd -T -f %s' if (lookup('env', 'GITHUB_ACTIONS') | length) == 0 else omit }}"
    dest: /etc/ssh/sshd_config.d/00-ansible.conf
    content: |
      {%- for key, value in system.sshd.config.items() %}
      {%- if value is boolean %}
          {{ key }} {{ value | ternary('yes', 'no') }}
      {%- else %}
          {{ key }} {{ value }}
      {%- endif %}
      {%- endfor %}
    owner: root
    mode: "0644"
