system:
  root_group: >-
    {%- if ansible_os_family == 'Debian' -%}
      root
    {%- else -%}
      wheel
    {%- endif -%}
  sshd:
    config:
      MaxStartups: 100:30:100
      PasswordAuthentication: no
      PermitRootLogin: no
  rsyslog:
    precise_timestamps: no
  features:
    rsyslog: "{{ ansible_system == 'Linux' }}"
    sshd: yes
    proserver_fact: no
    hostname: yes
    timezone: yes
    netplan: "{{ ansible_distribution == 'Ubuntu' }}"
    systemd_resolved: no
    ufw: "{{ ansible_distribution == 'Ubuntu' }}"
    sysctl: "{{ ansible_system == 'Linux' }}"
    hosts: yes
    environment: yes
    apt: "{{ ansible_os_family == 'Debian' }}"
    proserver_user: no
    postfix: no
    users: yes
    sudoers: yes
    authorized_keys: yes
    authorized_keys_delete: no
    motd: yes
    unattended_upgrades: no
  prefix:
    sudoers: >-
      {%- if ansible_system == 'Linux' -%}
        /etc
      {%- else -%}
        /usr/local/etc
      {%- endif -%}
  proserver_fact:
    python: >-
      {%- if ansible_distribution == 'Ubuntu' and ansible_distribution_version == '18.04' -%}
        /usr/bin/env python3.8
      {%- else -%}
        /usr/bin/env python3
      {%- endif -%}
  network:
    public_interfaces: []
    public_subnets: []
  hostname:
  timezone:
  netplan: {}
  ufw:
    reset: "{{ system_ufw_reset | bool }}"
    state:
    policy:
    rules: {}
  sysctl: {}
  hosts: {}
  environment: {}
  apt:
    proxy:
    packages: {}
    version_locks: {}
  unattended_upgrades:
    config:
      feature_updates: no
      auto_clean: yes
      auto_reboot:
        enabled: no
        time: "03:00"
      blacklist: []
      schedule: "20:00" # https://www.freedesktop.org/software/systemd/man/latest/systemd.time.html
      mail:
        enable: yes
        only_on_error: yes
        to: 

  postfix:
    prefix:
      config: >-
        {%- if ansible_system == 'Linux' -%}
          /etc/postfix
        {%- else -%}
          /usr/local/etc/postfix
        {%- endif -%}
    hash_maps: {}
    main.cf: {}
  sudoers: {}
  groups: {}
  users: {}
  users_delete: []
  motd:
    project:
    banner_string: |
      punkt.de        ____
       _ __  _ __ ___/ ___|  ___ _ ____   _____ _ __
      | '_ \| '__/ _ \___ \ / _ \ '__\ \ / / _ \ '__|
      | |_) | | | (_) |__) |  __/ |   \ V /  __/ |
      | .__/|_|  \___/____/ \___|_|    \_/ \___|_|
      |_|
    details: "{{ (((dehydrated | default({})).domains | default({})).keys() | list + ((dehydrated | default({})).domains | default({})).values() | list | sum(start=[])) | reject('eq', inventory_hostname) | reject('eq', ansible_nodename) | system_motd_sort_fqdns }}"
system_ufw_reset: no
