---
- name: Restart Postfix
  ansible.builtin.service:
    name: postfix
    state: restarted

- name: Restart sshd
  when: (lookup('env', 'GITHUB_ACTIONS') | length) == 0
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Reload systemd units
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted
