---
name: Test
run-name: Run molecule tests on the role
on:
  push:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies.
        run: pip install -r requirements.txt

      - name: Run ansible-lint
        run: "ansible-lint"

  molecule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create an openssh privilege separation directory
        run: |
          sudo mkdir -p /run/sshd
          sudo chmod 0755 /run/sshd

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies.
        run: |
          source .envrc

      - name: Run molecule
        run: ".venv/bin/molecule test"
